name = "MemoryLayouts"
uuid = "109d70c3-7bcd-434b-a7d9-3642108a1280"
keywords = ["memory-layout", "cache-optimization", "performance", "simd", "contiguous-memory"]
version = "0.1.1-DEV"
authors = ["Joris Pinkse <pinkse@gmail.com> and contributors"]
description = "Optimize your memory layout for maximum cache efficiency by making struct fields contiguous."

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[weakdeps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[extensions]
MemoryLayoutsAxisKeysExt = "AxisKeys"
MemoryLayoutsInlineStringsExt = "InlineStrings"
MemoryLayoutsNamedDimsExt = "NamedDims"
MemoryLayoutsOffsetArraysExt = "OffsetArrays"

[compat]
Aqua = "0.8"
AxisKeys = "0.2"
ConstructionBase = "1.6.0"
DataStructures = "0.19.3"
InlineStrings = "1.4.5"
JET = "0.11"
NamedDims = "1.2"
OffsetArrays = "1.17"
StyledStrings = "1.11.0, 1"
Test = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "InlineStrings", "JET", "Test"]
